# Generated by Django 2.0.5 on 2018-10-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181014_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='owner',
            field=models.CharField(max_length=1000),
        ),
    ]
