# Generated by Django 2.0.5 on 2018-10-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20181014_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='owner',
        ),
        migrations.AlterField(
            model_name='files',
            name='docfile',
            field=models.FileField(upload_to='my'),
        ),
    ]
