# Generated by Django 2.0.5 on 2018-10-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20181014_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='owner',
            field=models.CharField(default='h1', max_length=1000),
            preserve_default=False,
        ),
    ]
