# Generated by Django 2.0.5 on 2018-10-14 10:10

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_files_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='docfile',
            field=models.FileField(upload_to=user.models.user_directory_path),
        ),
    ]
