# Generated by Django 2.0.5 on 2018-10-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20181014_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='path',
            field=models.CharField(default='lol', max_length=1000),
            preserve_default=False,
        ),
    ]
