# Generated by Django 2.0.5 on 2018-10-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_files_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='docfile',
        ),
        migrations.AddField(
            model_name='files',
            name='_docfile',
            field=models.TextField(blank=True, db_column='docfile'),
        ),
    ]
