# Generated by Django 2.0.5 on 2018-10-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20181022_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='_docfile',
        ),
        migrations.AddField(
            model_name='files',
            name='docfile',
            field=models.BinaryField(db_column='docfile', null=True),
        ),
    ]
