# Generated by Django 2.0.5 on 2018-10-22 12:24

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20181022_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='docfile',
            field=models.FileField(default='la', upload_to=user.models.user_directory_path),
            preserve_default=False,
        ),
    ]
