# Generated by Django 2.0.5 on 2018-10-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20181022_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='docfile',
            field=models.BinaryField(),
        ),
    ]
