# Generated by Django 2.0.5 on 2018-10-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20181022_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='sha256',
            field=models.CharField(default='21dscxbg', max_length=1000),
            preserve_default=False,
        ),
    ]
