# Generated by Django 2.0.5 on 2018-10-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_files_sha256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='owner',
            field=models.CharField(max_length=1000),
        ),
    ]
